"""
Toy patent corpus for Phase 2 pipeline validation.

These 7 hand-written patents were created to test the two-stage
retrieval pipeline (abstract embedding -> FAISS -> claims rerank)
before the real Phase 1 G06T corpus is available. Once the real
corpus lands, this module is replaced by a loader over real data;
the pipeline code in src/embedding_pipeline.py does not change.
"""

TOY_PATENTS =[
    {
        "id": "P001",
        "title": "Image Classification Using Convolutional Neural Networks",
        "abstract": (
            "A computer implemented system for classifying digital images "
            "using a convolutional neural network. The system receives an "
            "input image and generates a predicted image category."
        ),
        "claims": (
            "A method comprising receiving an image, processing the image "
            "through multiple convolutional layers, and generating a "
            "classification label."
        ),
    },
    {
        "id": "P002",
        "title": "Medical Image Tumor Detection System",
        "abstract": (
            "A machine learning system for detecting tumors in medical "
            "images such as MRI and CT scans. The system analyzes image "
            "features to identify potential abnormal regions."
        ),
        "claims": (
            "A method comprising receiving a medical image, extracting "
            "visual features using a neural network, identifying abnormal "
            "regions, and generating a tumor detection result."
        ),
    },
    {
        "id": "P003",
        "title": "Autonomous Vehicle Object Detection",
        "abstract": (
            "A computer vision system for detecting vehicles, pedestrians, "
            "and road objects from images captured by cameras installed on "
            "an autonomous vehicle."
        ),
        "claims": (
            "A method comprising receiving camera images, processing the "
            "images using a deep neural network, detecting objects, and "
            "transmitting object location information to a vehicle control "
            "system."
        ),
    },
    {
    "id": "P004",
    "title": "Natural Language Document Summarization",
    "abstract": (
        "A system for automatically generating summaries of textual "
        "documents using transformer based neural networks and natural "
        "language processing techniques."
    ),
    "claims": (
        "A method comprising receiving a text document, processing the "
        "document using a transformer neural network, identifying "
        "important sentences, and generating a summary."
    ),
    },
    {
        "id": "P005",
        "title": "Facial Recognition Based Access Control",
        "abstract": (
            "A security system that identifies authorized individuals using "
            "facial recognition and grants access based on the identity "
            "prediction generated by a deep learning model."
        ),
        "claims": (
            "A method comprising capturing a facial image, generating "
            "facial features using a neural network, comparing the "
            "features with stored identities, and controlling access."
        ),
    },
    {
        "id": "TOY-MISSING-CLAIMS-01",
        "title": "Medical Image Segmentation System",
        "abstract": (
            "A computer vision system processes medical images "
            "to segment anatomical structures and identify regions "
            "of abnormal tissue."
        ),
        "claims": None,
    },
    {
        "id": "TOY-MISSING-CLAIMS-02",
        "title": "Neural Network System for Detecting Tumors",
        "abstract":( "A computer-implemented system uses a neural network to analyze medical images and identify tumors."),
        "claims": None,
    },
    {
        "id": "TOY-MISSING-CLAIMS-03",
        "title": "Image Processing System for Medical Diagnosis",
        "abstract":("An image processing system analyzes medical images to identify abnormal tissue."),
        "claims": None,
    },
]
